#!/usr/bin/env bash

# Run linux binaries from windows.
#
# Intended to be used with invoke-wsl-binary.bat which assumes this script
# is in ~/.local/bin.
# Converts DOS paths to WSL paths (Replace "X:" with "/mnt/x" and "\" with
# "/"). Also starts VcXsrv if it is not already running.

set -o nounset

if [[ -z $(cmd.exe /c tasklist | grep vcxsrv.exe) ]];
    then
        /mnt/c/Program\ Files/VcXsrv/vcxsrv.exe -ac -keyhook -multiwindow -wgl&!
fi
    export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0.0
    export LIBGL_ALWAYS_REDIRECT=1

declare -a adjusted_args

for arg in "$@"
do
    arg=${arg//\\/\/}
    if [[ $arg =~ ^([a-zA-Z]): ]]
    then
        driveLetter=${BASH_REMATCH[1]}
        adjusted_args+=("${arg/${driveLetter}:/\/mnt\/${driveLetter,,}}")
    else
        adjusted_args+=($arg)
    fi
done

"${adjusted_args[@]}"
